title: Practice Page for jekyll
author: GitHub User_Sheena
email: xernaysheena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Helvetica and Times New Roman walk into a bar,“Get out of here!” shouts the bartender. “We don’t serve your type.” 

# social links
twitter_username: @xernayd
github_username:  Sheena-Xernay

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
